plugins {
    `kotlin-dsl`
    `java-gradle-plugin`
    `maven-publish`
}

// PUBLISHED, and until #58 it was not — which made `/version` the one feature a consumer could not
// adopt at all. The identity the route serves is generated by this plugin and there is no other way
// to produce it, so a consumer without it would have to write `BuildIdentity` by hand: the library's
// job, done manually, in the one place where doing it manually reintroduces the defect
// `feature-build-identity` rule 1 exists to remove.
//
// It is not a `:kore-*` subproject and that is why it was missed twice over: the root
// `publishAllPublicationsToWipRepository` does not reach an included build, and B-48's completeness
// check read `include(":kore-*")` out of settings.gradle.kts — a form this build does not have. The
// check now walks the `kore-*` directories instead, which is the rule rather than the shape.
group = "io.github.youndie"
version = (findProperty("VERSION") as String?) ?: "0.1.0-SNAPSHOT"

// An INCLUDED BUILD rather than a subproject, because a plugin cannot be applied by the same build
// that compiles it. The portfolio's convention plugins use the same shape, and it is also what lets
// this be published on its own later.
kotlin {
    jvmToolchain(25)
}

dependencies {
    testImplementation(kotlin("test"))
    testImplementation(gradleTestKit())
}

tasks.named<Test>("test") { useJUnitPlatform() }

gradlePlugin {
    // `website` and `vcsUrl` are what `java-gradle-plugin` puts in the marker's POM; without them the
    // marker publishes with a description nobody can act on.
    website = "https://github.com/youndie/kore"
    vcsUrl = "https://github.com/youndie/kore.git"
    plugins {
        create("koreBuildIdentity") {
            id = "io.github.youndie.kore.build"
            implementationClass = "io.github.youndie.kore.gradle.BuildIdentityPlugin"
            displayName = "kore build identity"
            description = "Compiles the version, the commit and the build date into the binary"
        }
    }
}

publishing {
    // The same two repositories the four library modules use, for the same reasons — registered
    // unconditionally so a missing credential fails a PUT loudly instead of turning the publish into
    // a green no-op, and mirrored into `build/published` so the read-back verifies what was produced.
    repositories {
        maven {
            name = "wip"
            url = uri("https://reposilite.kotlin.website/snapshots")
            credentials {
                username = (findProperty("REPOSILITE_USER") as String?).orEmpty()
                password = (findProperty("REPOSILITE_SECRET") as String?).orEmpty()
            }
        }
        maven {
            name = "localCopy"
            url = File(rootDir.parentFile, "build/published").toURI()
        }
    }

    publications.withType(MavenPublication::class.java).configureEach {
        pom.name.set("kore-build")
        pom.description.set("kore — the Gradle plugin that compiles build identity into the binary")
        pom.url.set("https://github.com/youndie/kore")
        pom.licenses {
            license {
                name.set("MIT")
                url.set("https://github.com/youndie/kore/blob/main/LICENSE")
            }
        }
        pom.developers {
            developer {
                id.set("youndie")
                name.set("youndie")
            }
        }
        pom.scm {
            url.set("https://github.com/youndie/kore")
            connection.set("scm:git:https://github.com/youndie/kore.git")
        }
    }
}
